services:
  mongo:
    image: mongo:6.0
    container_name: rastro-mongo
    ports:
      - "27028:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rastro-net

  rastro-api:
    build:
      context: ./api
      dockerfile: RastroApi/Dockerfile
    container_name: rastro-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Mongo=mongodb://rastro-mongo:27017
    depends_on:
      - mongo
    networks:
      - rastro-net

volumes:
  mongo-data:

networks:
  rastro-net:
